### ISSUE TITLE
Ability to toggle sidebars

### ISSUE THREAD

**Issue by lachlanjc** [eveningkid/reacto#35]
- I was initially confused with the < button in the upper-left, assuming it would hide the file tree—maybe it should be a 🏠 icon instead
- I want the ability to toggle the sidebars closed.
  - Especially the right sidebar, as it takes up 1/4 of the screen space with nothing on it on a vertical display
  - Having a toggle on the right side of the top of the file tree would be handy too for when you're focusing on one file
- It'd also be awesome to have these under the View menu as well (keyboard shortcuts, anyone? :)

**Comment by eveningkid** [comment]
@lachlanjc a few suggestions for the back button:

<img width="209" alt="screenshot at mar 26 00-28-03" src="https://user-images.githubusercontent.com/7188494/37877414-7dff306e-308d-11e8-84b6-acf5b08bff02.png">
<img width="240" alt="screenshot at mar 26 00-34-01" src="https://user-images.githubusercontent.com/7188494/37877415-808587ca-308d-11e8-825b-655c67f557f6.png">
<img width="293" alt="screenshot at mar 26 00-34-23" src="https://user-images.githubusercontent.com/7188494/37877416-82ffbab6-308d-11e8-9757-0bc868feae54.png">

It can also be something different. I just hope it can remain coherent with everything else.

**Comment by eveningkid** [comment]
- I changed the "back" icon to a simple text (third screenshot from the previous post) d0d1235432300da38b3b843cbaad6f31eeccbae2 This can still be changed if you give your opinion, otherwise, we'll keep it this way.
- Can now toggle both file tree and brick selector using <kbd>Ctrl+Cmd+Left</kbd> and <kbd>+Right</kbd> bb8cf6a61c05052afd6b1225a2ef32f585e6768e Shortcuts could change if it's not handy enough (I tried a couple ones and this one seemed "ok"). Also, I believe the "sliding" animation isn't necessary, I'll probably remove it (it comes from `ant` css default).

Any feedback would be appreciated, anytime. :)

**Comment by lachlanjc** [comment]
Awesome @eveningkid. Excuse my ignorance, can I download a packaged release or do I need to set up the full codebase in order to try it out?

**Comment by eveningkid** [comment]
I think the quickest way for you, as you contribute a lot, is to clone the repo and build it somewhere. Any time there is an update you simply need to `git pull` and then call `yarn run electron:dev`. So you can keep your release in your applications folder but at the same time try experimental features this way. :)

[Steps to follow](https://github.com/eveningkid/reacto#contribute) (without needing to directly contribute actually). 

You can give some feedback when you're all set, whenever you have time!

**Comment by lachlanjc** [comment]
@eveningkid Got it set up, thank you! And these changes are looking really solid.
