### ISSUE TITLE
Performance problems while upgrading all dependencies

### ISSUE THREAD

**Issue by lachlanjc** [eveningkid/reacto#39]
Reacto dramatically slows down while upgrading all dependencies, but it speeds back up as soon as it's finished.

**Comment by eveningkid** [comment]
I observed similar side effects and I sadly have no idea why... I would wish someone could help me on this because I've checked it already but can't seem to find any way to solve this.

It feels like running any command (by spawning child processes with `utils.exec`) can quickly slowing down everything while it's running. Help would be extremely appreciated on this: how is atom dealing with this for example?

**Comment by eveningkid** [comment]
This issue has been fixed. Reacto is now using `yarn update --latest` instead. Way faster.
Also, the new update increased the performance for running commands in the background.
That means it all goes faster, without impacting too much the UI (if almost not at all). You can try it, it's been pushed. :)
